version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    #    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - net-prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    #    restart: always
    ports:
      - "3000:3000"
#    volumes:
#      #- ./conf/grafana:/etc/grafana
##      - ./data/prometheus/grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - net-prometheus

networks:
  net-prometheus: